name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v15
        uses: actions/setup-node@v1
        with:
          node-version: v15.x
      - run: yarn install
      - run: yarn run test
  coverage:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v15
        uses: actions/setup-node@v1
        with:
          node-version: v15.x
      - run: yarn install
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn run test:cov
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v15
        uses: actions/setup-node@v1
        with:
          node-version: v15.x
      - run: yarn install
      - run: yarn run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v15
        uses: actions/setup-node@v1
        with:
          node-version: v15.x
      - run: yarn install
      - run: yarn run build
